services:
  app:
    build:
      context: .
    ports:
      - "12000:3000"
    volumes:
      - .:/app/
    command: npm run dev
  db:
    image: postgres:17-alpine
    container_name: cat-plant-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: