services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
    tty: true
    command: npm run dev
    networks:
      - supabase_network_neko-plant

networks:
  supabase_network_neko-plant:
    external: true