create type "public"."reaction_type" as enum ('good', 'bad');

create table "public"."evaluation_reactions" (
    "id" integer generated by default as identity not null,
    "evaluation_id" integer not null,
    "user_id" integer not null,
    "created_at" timestamp with time zone not null default now(),
    "type" reaction_type not null
);


CREATE UNIQUE INDEX evaluation_reactions_pkey ON public.evaluation_reactions USING btree (id);

alter table "public"."evaluation_reactions" add constraint "evaluation_reactions_pkey" PRIMARY KEY using index "evaluation_reactions_pkey";

alter table "public"."evaluation_reactions" add constraint "evaluation_reactions_evaluation_id_fkey" FOREIGN KEY (evaluation_id) REFERENCES evaluations(id) not valid;

alter table "public"."evaluation_reactions" validate constraint "evaluation_reactions_evaluation_id_fkey";

alter table "public"."evaluation_reactions" add constraint "evaluation_reactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."evaluation_reactions" validate constraint "evaluation_reactions_user_id_fkey";

grant delete on table "public"."evaluation_reactions" to "anon";

grant insert on table "public"."evaluation_reactions" to "anon";

grant references on table "public"."evaluation_reactions" to "anon";

grant select on table "public"."evaluation_reactions" to "anon";

grant trigger on table "public"."evaluation_reactions" to "anon";

grant truncate on table "public"."evaluation_reactions" to "anon";

grant update on table "public"."evaluation_reactions" to "anon";

grant delete on table "public"."evaluation_reactions" to "authenticated";

grant insert on table "public"."evaluation_reactions" to "authenticated";

grant references on table "public"."evaluation_reactions" to "authenticated";

grant select on table "public"."evaluation_reactions" to "authenticated";

grant trigger on table "public"."evaluation_reactions" to "authenticated";

grant truncate on table "public"."evaluation_reactions" to "authenticated";

grant update on table "public"."evaluation_reactions" to "authenticated";

grant delete on table "public"."evaluation_reactions" to "service_role";

grant insert on table "public"."evaluation_reactions" to "service_role";

grant references on table "public"."evaluation_reactions" to "service_role";

grant select on table "public"."evaluation_reactions" to "service_role";

grant trigger on table "public"."evaluation_reactions" to "service_role";

grant truncate on table "public"."evaluation_reactions" to "service_role";

grant update on table "public"."evaluation_reactions" to "service_role";


