create table "public"."plant_have" (
    "id" integer generated by default as identity not null,
    "plant_id" integer not null,
    "user_id" integer not null,
    "created_at" timestamp with time zone not null default now()
);


CREATE UNIQUE INDEX "plant_ have_pkey" ON public.plant_have USING btree (id);

alter table "public"."plant_have" add constraint "plant_ have_pkey" PRIMARY KEY using index "plant_ have_pkey";

alter table "public"."plant_have" add constraint "plant_ have_plant_id_fkey" FOREIGN KEY (plant_id) REFERENCES plants(id) not valid;

alter table "public"."plant_have" validate constraint "plant_ have_plant_id_fkey";

alter table "public"."plant_have" add constraint "plant_ have_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."plant_have" validate constraint "plant_ have_user_id_fkey";

grant delete on table "public"."plant_have" to "anon";

grant insert on table "public"."plant_have" to "anon";

grant references on table "public"."plant_have" to "anon";

grant select on table "public"."plant_have" to "anon";

grant trigger on table "public"."plant_have" to "anon";

grant truncate on table "public"."plant_have" to "anon";

grant update on table "public"."plant_have" to "anon";

grant delete on table "public"."plant_have" to "authenticated";

grant insert on table "public"."plant_have" to "authenticated";

grant references on table "public"."plant_have" to "authenticated";

grant select on table "public"."plant_have" to "authenticated";

grant trigger on table "public"."plant_have" to "authenticated";

grant truncate on table "public"."plant_have" to "authenticated";

grant update on table "public"."plant_have" to "authenticated";

grant delete on table "public"."plant_have" to "service_role";

grant insert on table "public"."plant_have" to "service_role";

grant references on table "public"."plant_have" to "service_role";

grant select on table "public"."plant_have" to "service_role";

grant trigger on table "public"."plant_have" to "service_role";

grant truncate on table "public"."plant_have" to "service_role";

grant update on table "public"."plant_have" to "service_role";


