-- AI植物判定のレート制限用ログテーブル (セキュリティレビュー対応 issue #91)
--
-- identifyPlantFromImage は認証済みユーザーなら無制限に呼べ、1回ごとに有料の
-- 画像認識API (Gemini/OpenAI) を消費する。ユーザー単位で直近の実行回数を数えて
-- 制限するため、実行時刻を記録する軽量ログを用意する。
--
-- 書き込みはアプリの Prisma (特権接続) のみが行う。他テーブルと同様に
-- RLS 有効 + 書き込みポリシーなし + anon/authenticated の権限剥奪で
-- PostgREST 経由の直接アクセスを二重に遮断する。

create table if not exists public.plant_identification_logs (
    id bigint generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

-- ユーザー単位・時刻範囲での集計を高速化する
create index if not exists plant_identification_logs_user_created_idx
    on public.plant_identification_logs (user_id, created_at desc);

alter table public.plant_identification_logs enable row level security;

-- クライアント (anon/authenticated) からの直接アクセスは一切許可しない
revoke all on table public.plant_identification_logs from anon, authenticated;
