-- =============================================================
-- v2リデザイン: 植物安全DB → フォトSNS
-- 旧テーブル削除・新テーブル作成・RLS設定・ストレージ設定
-- =============================================================

-- -------------------------------------------------------------
-- 1. 旧テーブルの RLS ポリシー削除
-- -------------------------------------------------------------
DROP POLICY IF EXISTS "evaluations_select_all" ON public.evaluations;
DROP POLICY IF EXISTS "evaluation_reactions_select_all" ON public.evaluation_reactions;
DROP POLICY IF EXISTS "plant_images_select_approved" ON public.plant_images;
DROP POLICY IF EXISTS "plant_images_select_own" ON public.plant_images;
DROP POLICY IF EXISTS "plant_favorites_select_own" ON public.plant_favorites;
DROP POLICY IF EXISTS "plant_have_select_own" ON public.plant_have;

-- -------------------------------------------------------------
-- 2. 旧テーブル削除（依存関係の逆順）
-- -------------------------------------------------------------
DROP TABLE IF EXISTS public.evaluation_reactions;
DROP TABLE IF EXISTS public.plant_images;
DROP TABLE IF EXISTS public.plant_favorites;
DROP TABLE IF EXISTS public.plant_have;
DROP TABLE IF EXISTS public.evaluations;

-- -------------------------------------------------------------
-- 3. 旧 enum 型削除
-- -------------------------------------------------------------
DROP TYPE IF EXISTS public.evaluation_type;
DROP TYPE IF EXISTS public.reaction_type;
DROP TYPE IF EXISTS public.mood;

-- -------------------------------------------------------------
-- 4. 新テーブル作成: posts
-- -------------------------------------------------------------
CREATE TABLE "public"."posts" (
    "id"         integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id"    integer NOT NULL,
    "plant_id"   integer NOT NULL,
    "pet_id"     integer,
    "comment"    character varying,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."posts"
    ADD CONSTRAINT "posts_user_id_fkey"
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."posts"
    ADD CONSTRAINT "posts_plant_id_fkey"
    FOREIGN KEY (plant_id) REFERENCES public.plants(id) ON DELETE CASCADE;

ALTER TABLE "public"."posts"
    ADD CONSTRAINT "posts_pet_id_fkey"
    FOREIGN KEY (pet_id) REFERENCES public.pets(id) ON DELETE SET NULL;

CREATE INDEX "posts_plant_id_idx" ON public.posts (plant_id);
CREATE INDEX "posts_user_id_idx"  ON public.posts (user_id);
CREATE INDEX "posts_created_at_idx" ON public.posts (created_at DESC);

-- -------------------------------------------------------------
-- 5. 新テーブル作成: post_images
-- -------------------------------------------------------------
CREATE TABLE "public"."post_images" (
    "id"         integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "post_id"    integer NOT NULL,
    "image_url"  character varying NOT NULL,
    "order"      integer NOT NULL DEFAULT 0,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE "public"."post_images" ADD CONSTRAINT "post_images_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."post_images"
    ADD CONSTRAINT "post_images_post_id_fkey"
    FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

CREATE INDEX "post_images_post_id_idx" ON public.post_images (post_id);

-- -------------------------------------------------------------
-- 6. 新テーブル作成: post_likes
-- -------------------------------------------------------------
CREATE TABLE "public"."post_likes" (
    "id"         integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "post_id"    integer NOT NULL,
    "user_id"    integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE "public"."post_likes" ADD CONSTRAINT "post_likes_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."post_likes"
    ADD CONSTRAINT "post_likes_post_id_fkey"
    FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE "public"."post_likes"
    ADD CONSTRAINT "post_likes_user_id_fkey"
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."post_likes"
    ADD CONSTRAINT "post_likes_post_id_user_id_key" UNIQUE (post_id, user_id);

-- -------------------------------------------------------------
-- 7. 権限付与
-- -------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON public.posts       TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.post_images TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.post_likes  TO anon, authenticated, service_role;

GRANT USAGE, SELECT ON SEQUENCE public.posts_id_seq       TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.post_images_id_seq TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.post_likes_id_seq  TO anon, authenticated, service_role;

-- -------------------------------------------------------------
-- 8. RLS 有効化
-- -------------------------------------------------------------
ALTER TABLE public.posts       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes  ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- 9. RLS ポリシー: posts
-- -------------------------------------------------------------
-- 投稿は誰でも閲覧可能
CREATE POLICY "posts_select_all"
    ON public.posts FOR SELECT
    TO anon, authenticated
    USING (true);

-- 認証済みユーザーは自分の投稿を作成可能
CREATE POLICY "posts_insert_own"
    ON public.posts FOR INSERT
    TO authenticated
    WITH CHECK (
        user_id = (SELECT id FROM public.users WHERE auth_id = auth.uid())
    );

-- 認証済みユーザーは自分の投稿を削除可能
CREATE POLICY "posts_delete_own"
    ON public.posts FOR DELETE
    TO authenticated
    USING (
        user_id = (SELECT id FROM public.users WHERE auth_id = auth.uid())
    );

-- -------------------------------------------------------------
-- 10. RLS ポリシー: post_images
-- -------------------------------------------------------------
-- 投稿画像は誰でも閲覧可能
CREATE POLICY "post_images_select_all"
    ON public.post_images FOR SELECT
    TO anon, authenticated
    USING (true);

-- 認証済みユーザーは自分の投稿に紐づく画像を作成可能
CREATE POLICY "post_images_insert_own"
    ON public.post_images FOR INSERT
    TO authenticated
    WITH CHECK (
        post_id IN (
            SELECT id FROM public.posts
            WHERE user_id = (SELECT id FROM public.users WHERE auth_id = auth.uid())
        )
    );

-- 認証済みユーザーは自分の投稿画像を削除可能
CREATE POLICY "post_images_delete_own"
    ON public.post_images FOR DELETE
    TO authenticated
    USING (
        post_id IN (
            SELECT id FROM public.posts
            WHERE user_id = (SELECT id FROM public.users WHERE auth_id = auth.uid())
        )
    );

-- -------------------------------------------------------------
-- 11. RLS ポリシー: post_likes
-- -------------------------------------------------------------
-- いいねは誰でも閲覧可能
CREATE POLICY "post_likes_select_all"
    ON public.post_likes FOR SELECT
    TO anon, authenticated
    USING (true);

-- 認証済みユーザーは自分のいいねを追加可能
CREATE POLICY "post_likes_insert_own"
    ON public.post_likes FOR INSERT
    TO authenticated
    WITH CHECK (
        user_id = (SELECT id FROM public.users WHERE auth_id = auth.uid())
    );

-- 認証済みユーザーは自分のいいねを削除可能
CREATE POLICY "post_likes_delete_own"
    ON public.post_likes FOR DELETE
    TO authenticated
    USING (
        user_id = (SELECT id FROM public.users WHERE auth_id = auth.uid())
    );

-- -------------------------------------------------------------
-- 12. ストレージ: evaluations バケットのポリシー削除
-- -------------------------------------------------------------
DROP POLICY IF EXISTS "Public evaluations are viewable by everyone"   ON storage.objects;
DROP POLICY IF EXISTS "Users can delete their own evaluation images"   ON storage.objects;
DROP POLICY IF EXISTS "Users can update their own evaluation images"   ON storage.objects;
DROP POLICY IF EXISTS "Users can upload their own evaluation images"   ON storage.objects;

-- -------------------------------------------------------------
-- 13. ストレージ: posts バケット作成
-- -------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('posts', 'posts', true)
ON CONFLICT (id) DO NOTHING;

-- -------------------------------------------------------------
-- 14. ストレージ: posts バケットのポリシー設定
-- -------------------------------------------------------------
CREATE POLICY "posts_storage_select_all"
    ON storage.objects FOR SELECT
    TO anon, authenticated
    USING (bucket_id = 'posts');

CREATE POLICY "posts_storage_insert_authenticated"
    ON storage.objects FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'posts' AND auth.uid() IS NOT NULL);

CREATE POLICY "posts_storage_update_own"
    ON storage.objects FOR UPDATE
    TO authenticated
    USING (bucket_id = 'posts' AND auth.uid() = owner);

CREATE POLICY "posts_storage_delete_own"
    ON storage.objects FOR DELETE
    TO authenticated
    USING (bucket_id = 'posts' AND auth.uid() = owner);
